controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

download_pdf:
    path: /download-pdf/{filename}
    controller: App\Controller\PortfolioController::downloadPdf
    requirements:
        filename: .+
