<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVs0t669\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVs0t669/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVs0t669.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVs0t669\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVs0t669\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vs0t669',
    'container.build_id' => '34e57474',
    'container.build_time' => 1744489543,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVs0t669');
